config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :first, presence: true
  validates :second, presence: true
  validates :considerations, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ingredients, dependent: :destroy
	before_save {self.email = email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
			BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :correct_user, only: :destroy
	def create
		@ingredient = current_user.ingredients.build(ingredient_params)
		if @ingredient.save
			flash[:success] = "Profile updated!"
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def destroy
		@ingredient.destroy
		flash[:success] = "Ingredients deleted"
		redirect_to request.referrer || root_url
	end

	private

		def ingredient_params
			params.require(:ingredient).permit(:first, :second, :considerations)
		end

		def correct_user
			@ingredient = current_user.ingredients.find_by(id: params[:id])
			redirect_to root_url if @ingredient.nil?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  	render 'new'
 	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@ingredient = current_user.ingredients.build if logged_in?
  	@ingredients = Ingredient.all
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @ingredient = current_user.ingredients.build if logged_in?
    @ingredients = @user.ingredients
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private
	  def user_params
	  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title='')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user?(user)
	    user == current_user
	  end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/ingredients/_ingredient.html.erb
<ul class="ingredient" id="ingredient-<%= ingredient.id %>">
	
	<li class="first"><h4>Fruit/Vegetable:</h4> <%= ingredient.first %></li>
	<li class="second"><h4>Protein/Grain:</h4> <%= ingredient.second %></li>
	<li class="considerations"><h4>Dietary Considerations:</h4> <%= ingredient.considerations %></li>
</ul>
<% if current_user?(ingredient.user) %>
      <%= link_to "delete", ingredient, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="header-container">
		<%= link_to "salad club", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<% if logged_in? %>
				<li><%= link_to "Users", '#' %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", '#' %></li>
						<li class="divider"></li>
						<li>
							<%= link_to "Log out", logout_path, method: "delete" %>
						</li>
					</ul>
				</li>
				<% else %>
				<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %>
	</div>
	<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">
		The form contains <%= pluralize(object.errors.count, "error") %>
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_ingredient_form.html.erb
<%= form_for(@ingredient) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :first, placeholder: "Enter a fruit or vegetable" %>
	</div>
	<div class="field">
		<%= f.text_area :second, placeholder: "Enter a protein or grain" %>
	</div>
	<div class="field">
		<%= f.text_area :considerations, placeholder: "Do you have any dietary considerations?" %>
	</div>
	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
 <h1>About</h1>
 <p>
   The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
   Tutorial</em></a> is a
   <a href="http://www.railstutorial.org/book">book</a> and
   <a href="http://screencasts.railstutorial.org/">screencast series</a>
   to teach web development with
   <a href="http://rubyonrails.org/">Ruby on Rails</a>.
   This is the sample application for the tutorial.
 </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
	<aside class="col-md-4">
		<ul class="ingredients clearfix">
			
			<ul class="fruits-n-veg">
			<h3>Fruits &amp; Vegetables</h3>
			<% @ingredients.each do |ingredient| %>
				<li>
					<%= ingredient.first %>
				</li>
			<% end %>
			</ul>	
			<ul class="protein-n-grains">
			<h3>Proteins, Dairy &amp; Grains</h3>
			<% @ingredients.each do |ingredient| %>
				<li>
					<%= ingredient.second %>
				</li>
			<% end %>
			</ul>
			
		</ul>
	</aside>
</div>
<% else %>
	<div class="home">	
		<h1>Salad Club</h1>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary sign-up" %>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title,'Sign up')%>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<div>
		<% if @user.ingredients.any? %>
		<h3><%= @user.name %>'s Salad Day Profile</h3>	
			<%= render @ingredients %>
		<% end %>
	</div>
	<% if logged_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="ingredient_form">
				<%= render 'shared/ingredient_form' %>
			</section>
		</aside>
	</div>
	<% end %>
</div>